server:
  port: 8083

spring:
  application:
    name: task-service
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/tasksDB
    username: root
    password: sudo0047
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
