# application.yml
server:
  port: 8083

spring:
  application:
    name: task-service
  datasource:
    url: jdbc:mysql://localhost:3306/tasks
    username: root
    password: sudo0047
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

feign:
  client:
    config:
      project-service:
        url: http://localhost:8082
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: basic
      user-service:
        url: http://localhost:8081
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: basic

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

jwt:
  secret: nzPhnXtBD7CHcNEEKjIrEtN3zRR/6SDafOwgbGAhWhDWIQiopogFfrTt8k9PWBvczlzhoeCOgNajfD8z+fyNYA==
  expiration: 3600