server:
  port: 8082

spring:
  application:
    name: project-service
  datasource:
    url: jdbc:mysql://localhost:3306/projects
    username: root
    password: sudo0047
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: nzPhnXtBD7CHcNEEKjIrEtN3zRR/6SDafOwgbGAhWhDWIQiopogFfrTt8k9PWBvczlzhoeCOgNajfD8z+fyNYA==
  expiration: 3600

springdoc:
  swagger-ui:
    url: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: true
  api-docs:
    path: /v3/api-docs

feign:
  client:
    config:
      user-service:
        url: http://localhost:8081
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: basic
      task-service:
        url: http://localhost:8083
        connect-timeout: 5000
        read-timeout: 5000 
        logger-level: basic